[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["szablon_wydanie.docx", "szablon_zdanie.docx"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
